/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

export const amplify= {
Auth:{
    userPoolId:"us-east-1_QxuAJ1j6e",
    region:'us-east-1',
    userPoolWebClientId:"1t28vn1qo3d2tvk0u1preu30f6",
    oauth: {
        domain:"example-login.auth.us-east-1.amazoncognito.com" ,
        scope:[
                    "phone",
                    "email",
                    "openid",
                    "profile",
                    "aws.cognito.signin.user.admin"
                ], 
        redirectSignIn:"http://localhost:4200" ,
        redirectSignOut: "http://localhost:4200" ,
        responseType: "code",
      },
}
};


export default amplify;
